### ISSUE TITLE
Fix format of output CSV

### ISSUE THREAD

**Issue by HeatherMikan** [GTJuniorDesign0100-2020/anti-malarial-MCMC-bayesian-algorithm#37]

**Comment by JHDeerin** [comment]
Adding some details to this:
- Fix `microsatellite_correction.csv` so that datapoints are printed on the correct lines (currently appear to be appended below the sample, which we don't want)
- Create `<site>_state_parameters.csv` files (currently not being generated; I think all the data for this is stored during the run, but it's never made into a `.csv` at any point)
- Note that currently the 1st line of `<site>_summary_statistics.csv` and `probability_of_recrudescence.csv` is printed as "0", when it's "V1" in the original R script (probably should be fixed?)

**Comment by JHDeerin** [comment]
Also, some improvements we can make to the original CSV output format (based on conversation w/ Mat last week in meeting):

- `<site>_posterior.csv` should have the 1st column w/ numbers replaced with the a "Sample ID" column, containing the corresponding Sample ID for each row (e.g. `BQ17-269 Day 0` or something)
- Ditto for `<site>_state_parameters.csv` - replace the 1st column indices with the actual variable name each row represents
- `<site>_summary_statistics.csv` should use more descriptive names:
    - Rename Q to "Probability of Missing Allele"
    - Rename D to "Error Rate" (I think?)
    - Label the 1st group of loci as "Frequency of Most Common Allele", and make sure the 2 columns are marked clearly as "Locus Name" and "Mean w/ Interquartile Range (25%, 75%)"
    - Label the 2nd group of loci as "Simpson's Diversity Index" (w/ same column labels as above)
    - Rename Mean Diversity to "Average Simpson's Index"
- `probability_of_recrudescence.csv` should have the Sample IDs as the new 1st column (just like `microsatellite_correction.csv`), recrudescence probability as 2nd
